### ISSUE TITLE
Using bdsmail with i2pd produces naming lookup error

### ISSUE THREAD

**Issue by mathiasfriman** [PurpleI2P/i2pd#641]
I've tried majestrates bdsmail for sending SMTP messages back and forth between my i2pd machines. We discussed this on IRC, so I'll just leave this as a reminder.

This outlines the sending of an email to a host not in the address book:

    00:09:05@682/debug - SAM: new connection from 127.0.0.1:49342
    00:09:05@682/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    00:09:05@682/debug - SAM: naming lookup: NAME=onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p
    00:09:05@682/debug - Addressbook: Requested, but not found: /home/user/.i2pd/addressbook/bo/onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32
    00:09:05@682/error - SAM: naming failed, unknown address onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p
    00:09:05@682/error - SAM: read error: End of file

Both services are up and running, and sending to oneself works, so it has something to do with the lookup.

**Comment by majestrate** [comment]
this should be fixed in lasted bdsmail

**Comment by mathiasfriman** [comment]
Sadly it seems to persist. :/ I did a git pull just now and recompiled, but the problem still occurs..

    INFO[0380] outbound message queued: /root/source/bdsmail/outbound/new/7afd2a271a3d799c147464860821016.elementary01 
    INFO[0390] Sending outbound mail /root/source/bdsmail/outbound/new/7afd2a271a3d799c147464860821016.elementary01 
    INFO[0390] Delivering  mail to admin@onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p from root <admin@ejvxvge5mqs2pn2qnrummcadftjsyneesm6if7svykdrgpj6nkgq.b32.i2p> 
    WARN[0390] failed to resolve onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p: NAMING REPLY RESULT=INVALID_KEY NAME=onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p
 
    WARN[0390] failed to deliver message to admin@onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p from root <admin@ejvxvge5mqs2pn2qnrummcadftjsyneesm6if7svykdrgpj6nkgq.b32.i2p>: NAMING REPLY RESULT=INVALID_KEY NAME=onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p

**Comment by orignal** [comment]
@mathiasfriman  please provide i2pd log messages starting from "SAM: "

**Comment by mathiasfriman** [comment]
This is all SAM messages from starting the router to the failed sending of message:

    19:39:21@359/debug - SAM: new connection from 127.0.0.1:48721
    19:39:21@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    19:39:21@359/debug - SAM: session create: STYLE=STREAM ID=2nA9XDHvDb3Njg DESTINATION=G9Ds4ZYh7JwzNzaiScWjD0XYdID9dR0t8CMfKa-JuGkoCq2Dox2OYMPH6zgKOIP31obxRuLHYfZfHaIBMKtHJln44EltvRQJCA3t0xvOLulUwtOhbdeB0KOaVWV3aAYZ-ZnBuexTurrHPykk5tWqqtajMt5gaybAUBp7oSPjVk~154usYUUZXGpyNm9569xeo4uc4kMpaorL986wMg8dJO-OBCWGla1CS2RSeqqIXoIxIsS7I0HSpqDeB7WL6DOqrCSEZf4idJUSEvR4g0dbvkjcxnvfCCk1GjLXg-mz9dF3mkkd0SE81w0RCZNqmP0~DlN6EJgsYEsti3VJn8FBowqhnyIHp7Yg-ol0zomWAiLDAdfwiXdpqOXFHRF-BKxJYZkVE7HSKf4V-L5p9kJ4pJvpiBijwiXoNr4siqbsgx3aFK3HfSx7tXdhSLinCyOOhq5P58K3TJ5vs~V49IvPbyGCNlh6L4nYMhgbO6yPeeSDM1kLn7dVcsBP6calnkTsAAAAaQN8DmR~s7Of~Ew22hqz8HbdjcIlpAO2bOcS6L38UCfyAMsyhaTOAg8gjVtI1xAY4p-9n2c-8gfB~DcXkkm8HFnFd1lerLjafm77v27t~5pftLgxFq5GYRnMZ15fPrKVJagZ1uqzSLZtjLbjvEgGPk4iOz8YfVEE0ccFa3TDSNeHzrs7hKc3KokysMMYswCNsrQH29DxFdDb6cSIJrCZ-MmVF3Hhc1Ncet7KOAVAI~ACtGNNAYH9Dc693E-o-B4Mc9gkd8D~2xp5jCJDeqkeaEftdcmba5AtHT6O-~xGQ-~p7lSw4WEpHWnjnbACtZv8~cA6FOsBZgn79CcDGfrlMEDPI1VH-75wQ-wHLh6p64Z-LHFI
    19:39:21@359/info - Destination: Local address ejvxvge5mqs2pn2qnrummcadftjsyneesm6if7svykdrgpj6nkgq created
    19:40:01@359/debug - SAM: new connection from 127.0.0.1:48734
    19:40:01@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    19:40:01@359/debug - SAM: stream accept: ID=2nA9XDHvDb3Njg SILENT=false
    19:48:11@359/debug - SAM: new connection from 127.0.0.1:48811
    19:48:11@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    19:48:11@359/debug - SAM: naming lookup: NAME=onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p
    19:48:11@359/error - SAM: naming failed, unknown address onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p
    19:48:11@359/error - SAM: read error: End of file
    19:48:13@359/debug - SAM: new connection from 127.0.0.1:48812
    19:48:13@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    19:48:13@359/debug - SAM: naming lookup: NAME=onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p
    19:48:13@359/error - SAM: naming failed, unknown address onfntovle5ptvcjptcdt2oumwsnbc6jbebqakswfx5j5hglj2f5q.b32.i2p
    19:48:13@359/error - SAM: read error: End of file
etc.

**Comment by mathiasfriman** [comment]
Crap. Sit tight, I ran this on a machine without an updated i2pd. Give me a while to check up on this.

**Comment by orignal** [comment]
@mathiasfriman  nothing has been changed in i2pd regarding this issue.
bsdmail just tried to request a destination without session, that's why it failed.

**Comment by mathiasfriman** [comment]
Ok, so now I have setup bdsmail on my well integrated raspberry pi (it works, thanks @majestrate !)

I have three i2pd routers with bdsmail now. Two well integrated routers (**pi** and **o**) with 2500+ transit tunnels, and one (**hp**) which lingers along with a couple of kbytes/second of traffic and just a couple transit tunnels.

After I installed bdsmail on **pi**, I could immediately send bdsmail to **o**, and to **hp**. 
But I couldn't send anything from **hp** until i'd sent bdsmail from **o** and **pi**

So it seems that for bdsmail to function properly, the i2pd router needs to be well integrated?

Here's the i2pd log from **hp** when a bdsmail was first being sent from **hp** to **pi** and not being able to resolve the address, then receiving a mail from **pi** to **hp** and suddenly being able to resolve the address:

    22:07:00@359/debug - SAM: new connection from 127.0.0.1:51983
    22:07:00@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:07:00@359/debug - SAM: naming lookup: NAME=ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:07:00@359/error - SAM: naming failed, unknown address ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:07:00@359/error - SAM: read error: End of file
    22:07:48@965/debug - SAM: incoming I2P connection for session 2nA9XDHvDb3Njg
    22:07:48@965/warn - SAM: I2P acceptor has been reset
    22:07:48@359/debug - SAM: new connection from 127.0.0.1:51988
    22:07:48@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:07:48@359/debug - SAM: stream accept: ID=2nA9XDHvDb3Njg SILENT=false
    22:08:10@359/debug - SAM: new connection from 127.0.0.1:51990
    22:08:10@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:08:10@359/debug - SAM: naming lookup: NAME=ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:08:10@359/error - SAM: read error: End of file
    22:09:08@359/debug - SAM: new connection from 127.0.0.1:51999
    22:09:08@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:09:08@359/debug - SAM: naming lookup: NAME=ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:09:08@359/error - SAM: read error: End of file
    22:09:08@359/debug - SAM: new connection from 127.0.0.1:52000
    22:09:08@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:09:08@359/debug - SAM: new connection from 127.0.0.1:52001
    22:09:08@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:09:08@359/debug - SAM: naming lookup: NAME=ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:09:08@359/error - SAM: read error: End of file
    22:09:08@359/debug - SAM: stream connect: ID=2nA9XDHvDb3Njg DESTINATION=pbAH6D--s2HMsHg2plzSCTQg0LPwbJtQKziBXjihl8dwdCbYUqIXkPhid~wy88QkJ6B0OxtCzxANxt-7CxLd8hZXRut-CzZWKWH2QeubAA2GKIq1MV-zoWISh-XkYjQZbV4RhSWK-xFZgLxTBG0WqcU4LRKGhGE-hsm3yNcP-HbL-m3h2FMcGeKsw~pu-E5G0JRfz7a29Q~uxoYPxzNuwa1tW28ur49tePDtKFyJU2u1AhvnBlpuhS3PZCKz2bbO3813nVP-dUdrxxU9zZAxQyFUBTm65pATJMJovr2aWPM4muBOxUilOXGmRkza3aVF38cvdPew-RgKX3tJB9ItDUYvpB7N2QPdKUBYr7UBksxe3xnk1ZwTuljvZswSR-Qkp16qPZDcqtU~LukIvJv0fUaSaJuXcynUCXAKL5AfyKq2QU5wcxSlrnHkMGqS~meCRkxPH-2Dm5qpMvXwsHXtuNHOIxvyDvS1Tuk0wfLWR~k~RIr2XmlDqjBVhSaAO1J4AAAA SILENT=false

Hope you could understand what I try to say..

**Comment by mathiasfriman** [comment]
Thought I just give you the full log from when trying to send a message to actually succeeding in sending it.

Inbetween these log excerpts bdsmail receives a mail from the router we try to send to. It seems that is why it succeeds in sending the mail. Also, the `/home/user/.i2pd/addressbook/be/ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32` is created during this time, probably during the **stream connect** stage.

    -rw-rw---- 1 user user 387 sep 23 22:09 /home/user/.i2pd/addressbook/be/ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32

Full log: http://paste.debian.net/838011/

    22:07:00@359/debug - SAM: new connection from 127.0.0.1:51983
    22:07:00@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:07:00@359/debug - SAM: naming lookup: NAME=ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:07:00@359/debug - Addressbook: Requested, but not found: /home/user/.i2pd/addressbook/be/ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32
    22:07:00@359/error - SAM: naming failed, unknown address ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:07:00@359/error - SAM: read error: End of file
    [..]
    22:09:08@359/debug - SAM: new connection from 127.0.0.1:51999
    22:09:08@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:09:08@359/debug - SAM: naming lookup: NAME=ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:09:08@359/error - SAM: read error: End of file
    22:09:08@359/debug - SAM: new connection from 127.0.0.1:52000
    22:09:08@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:09:08@359/debug - SAM: new connection from 127.0.0.1:52001
    22:09:08@359/debug - SAM: handshake HELLO VERSION MIN=3.0 MAX=3.0
    22:09:08@359/debug - SAM: naming lookup: NAME=ebziqa2c6kox5xlmnamza7bir7edkurm7gzblgkk5754dpru6bya.b32.i2p
    22:09:08@359/error - SAM: read error: End of file
    22:09:08@359/debug - SAM: stream connect: ID=2nA9XDHvDb3Njg DESTINATION=pbAH6D--s2HMsHg2plzSCTQg0LPwbJtQKziBXjihl8dwdCbYUqIXkPhid~wy88QkJ6B0OxtCzxANxt-7CxLd8hZXRut-CzZWKWH2QeubAA2GKIq1MV-zoWISh-XkYjQZbV4RhSWK-xFZgLxTBG0WqcU4LRKGhGE-hsm3yNcP-HbL-m3h2FMcGeKsw~pu-E5G0JRfz7a29Q~uxoYPxzNuwa1tW28ur49tePDtKFyJU2u1AhvnBlpuhS3PZCKz2bbO3813nVP-dUdrxxU9zZAxQyFUBTm65pATJMJovr2aWPM4muBOxUilOXGmRkza3aVF38cvdPew-RgKX3tJB9ItDUYvpB7N2QPdKUBYr7UBksxe3xnk1ZwTuljvZswSR-Qkp16qPZDcqtU~LukIvJv0fUaSaJuXcynUCXAKL5AfyKq2QU5wcxSlrnHkMGqS~meCRkxPH-2Dm5qpMvXwsHXtuNHOIxvyDvS1Tuk0wfLWR~k~RIr2XmlDqjBVhSaAO1J4AAAA SILENT=false

**Comment by orignal** [comment]
It needs to be fixed at bsdmail side

**Comment by majestrate** [comment]
I believe this should've been fixed in latest revision of bdsmail, I have tested this via multiple i2pd instances, all succeed.

please continue this on bdsmail issue tracker thnx.
